# Generated by Django 5.1.4 on 2024-12-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateDb',
            fields=[
                ('reg_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rank_of_12_month', models.FloatField(blank=True, null=True)),
                ('rank_of_24_month', models.FloatField(blank=True, null=True)),
                ('rank_of_36_month', models.FloatField(blank=True, null=True)),
                ('rank_of_48_month', models.FloatField(blank=True, null=True)),
                ('rank_of_60_month', models.FloatField(blank=True, null=True)),
                ('rank_last_update', models.DateTimeField(blank=True, null=True)),
                ('fund_type', models.IntegerField(blank=True, null=True)),
                ('type_of_invest', models.CharField(blank=True, max_length=255, null=True)),
                ('fund_size', models.BigIntegerField(blank=True, null=True)),
                ('initiation_date', models.DateTimeField(blank=True, null=True)),
                ('daily_efficiency', models.FloatField(blank=True, null=True)),
                ('weekly_efficiency', models.FloatField(blank=True, null=True)),
                ('monthly_efficiency', models.FloatField(blank=True, null=True)),
                ('quarterly_efficiency', models.FloatField(blank=True, null=True)),
                ('six_month_efficiency', models.FloatField(blank=True, null=True)),
                ('annual_efficiency', models.FloatField(blank=True, null=True)),
                ('statistical_nav', models.FloatField(blank=True, null=True)),
                ('efficiency', models.FloatField(blank=True, null=True)),
                ('cancel_nav', models.FloatField(blank=True, null=True)),
                ('issue_nav', models.FloatField(blank=True, null=True)),
                ('dividend_interval_period', models.BigIntegerField(blank=True, null=True)),
                ('guaranteed_earning_rate', models.FloatField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('net_asset', models.BigIntegerField(blank=True, null=True)),
                ('estimated_earning_rate', models.FloatField(blank=True, null=True)),
                ('invested_units', models.BigIntegerField(blank=True, null=True)),
                ('articles_of_association_link', models.URLField(blank=True, null=True)),
                ('prospectus_link', models.URLField(blank=True, null=True)),
                ('website_address', models.URLField(blank=True, null=True)),
                ('manager', models.CharField(max_length=255)),
                ('manager_seo_register_no', models.BigIntegerField(blank=True, null=True)),
                ('guarantor_seo_register_no', models.BigIntegerField(blank=True, null=True)),
                ('auditor', models.CharField(blank=True, max_length=255, null=True)),
                ('custodian', models.CharField(blank=True, max_length=255, null=True)),
                ('guarantor', models.CharField(blank=True, max_length=255, null=True)),
                ('beta', models.FloatField(blank=True, null=True)),
                ('alpha', models.FloatField(blank=True, null=True)),
                ('is_completed', models.BooleanField(blank=True, null=True)),
                ('five_best', models.FloatField(blank=True, null=True)),
                ('stock', models.FloatField(blank=True, null=True)),
                ('bond', models.FloatField(blank=True, null=True)),
                ('other', models.FloatField(blank=True, null=True)),
                ('cash', models.FloatField(blank=True, null=True)),
                ('deposit', models.FloatField(blank=True, null=True)),
                ('fund_unit', models.FloatField(blank=True, null=True)),
                ('commodity', models.FloatField(blank=True, null=True)),
                ('fund_publisher', models.BigIntegerField(blank=True, null=True)),
                ('small_symbol_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ins_code', models.CharField(blank=True, max_length=255, null=True)),
                ('fund_watch', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dataBorsDj2',
            },
        ),
    ]
